新开一个node服务器用于编译Markdown；去除对 jsv8 库的依赖；新增数据库索引
* 基于 jsv8 的 php 旧代码仍保留在代码库中
* 可以通过修改 meta 表中的内容来切换 Markdown 的编译模式（jsv8 或 node）
* 除更新 Markdown 编译功能外，为优化数据库查询速度，还增加了一些新的索引

diff --git a/docker/prepare b/docker/prepare
--- a/docker/prepare
+++ b/docker/prepare
@@ -36,6 +36,25 @@ installAptPackages() {
         return 1
     fi
 
+    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash - &&
+    apt-get install -y nodejs &&
+    npm install npm@latest -g
+    if [ $? -ne 0 ]; then
+        echo -e "\033[1;91m"
+        echo "UOJ ERROR: FAILED to install nodejs."
+        echo -e "\033[0m"
+        return 1
+    fi
+
+    npm install pm2@latest -g
+    if [ $? -ne 0 ]; then
+        echo -e "\033[1;91m"
+        echo "UOJ ERROR: FAILED to install pm2."
+        echo -e "\033[0m"
+        return 1
+    fi
+
+
     python3.9 -m pip install pip --upgrade
     python3.9 -m pip install requests --upgrade
 
diff --git a/docker/setup b/docker/setup
--- a/docker/setup
+++ b/docker/setup
@@ -54,8 +54,36 @@ initUOJ() {
 		return 1
 	fi
 
-	cd /opt/uoj/web && chmod +x /root/composer-setup.sh && /root/composer-setup.sh
+	cd /opt/uoj/web && chmod +x /root/composer-setup.sh
 	if [ $? -ne 0 ]; then
+		echo -e "\033[1;91m"
+		echo "UOJ ERROR: FAILED to setup Composer."
+		echo -e "\033[0m"
+		return 1
+	fi
+	
+	/root/composer-setup.sh
+	if [ $? -ne 0 ]; then
+		return 1
+	fi
+
+	cd /opt/uoj/web &&
+	npm install
+	if [ $? -ne 0 ]; then
+		echo -e "\033[1;91m"
+		echo "UOJ ERROR: FAILED to execute npm install."
+		echo -e "\033[0m"
+		return 1
+	fi
+
+	mkdir /var/www/.pm2 &&
+	chown www-data /var/www/.pm2 &&
+	sudo -u www-data pm2 start app/aux/index.js --name aux &&
+	sudo -u www-data pm2 stop aux
+	if [ $? -ne 0 ]; then
+		echo -e "\033[1;91m"
+		echo "UOJ ERROR: FAILED to setup uoj aux server."
+		echo -e "\033[0m"
 		return 1
 	fi
 	
@@ -146,6 +174,5 @@ cd /root &&
 rm * -rf &&
 printf "\n\n==> Installation finished!\n" &&
 echo -e "\033[1;91m" &&
-echo "UOJ NOTICE: If you want to use blog editor, PLEASE INSTALL jsv8 BY YOURSELF." &&
 echo "UOJ NOTICE: If you want to support Java 14, PLEASE INSTALL openjdk-14-jdk BY YOURSELF (or you can simply delete this language)." &&
 echo -e "\033[0m"
diff --git a/docker/up b/docker/up
--- a/docker/up
+++ b/docker/up
@@ -1,35 +1,51 @@
 #!/bin/bash
 
+succ=1
 if ! service ntp start; then
     echo -e "\033[1;91m"
 	echo "UOJ ERROR: ntp did not start successfully!"
     echo -e "\033[0m"
+    succ=0
 fi
 
 if ! service mysql start; then
     echo -e "\033[1;91m"
 	echo "UOJ ERROR: mysql did not start successfully!"
     echo -e "\033[0m"
+    succ=0
 fi
 
 if ! service apache2 start; then
     echo -e "\033[1;91m"
 	echo "UOJ ERROR: apache2 did not start successfully!"
     echo -e "\033[0m"
+    succ=0
 fi
 
 if ! svnserve -d -r /var/svn; then
     echo -e "\033[1;91m"
 	echo "UOJ ERROR: svn did not start successfully!"
     echo -e "\033[0m"
+    succ=0
 fi
 
 if ! su local_main_judger -c '~/judge_client/judge_client start'; then
     echo -e "\033[1;91m"
 	echo "UOJ ERROR: judger did not start successfully!"
     echo -e "\033[0m"
+    succ=0
 fi
 
-echo "UOJ starts successfully!"
+cd /opt/uoj/web && sudo -u www-data pm2 start app/aux/index.js --name aux
+if [ $? -ne 0 ]; then
+    echo -e "\033[1;91m"
+	echo "UOJ ERROR: uoj aux server did not start successfully!"
+    echo -e "\033[0m"
+    succ=0
+fi
+
+if [ $succ -eq 1 ]; then
+    echo "UOJ starts successfully!"
+fi
 
 exec bash
