2022.03.23 最新版本
公开了目前官网的最新代码。

改进了许多问题，修正了许多 BUG。重构了核心代码，完善了部分文档。

Closes #6, closes #14, closes #64, closes #79.

diff --git a/docker/up b/docker/up
--- a/docker/up
+++ b/docker/up
@@ -1,10 +1,35 @@
-#!/bin/sh
+#!/bin/bash
 
-service ntp start
-service apache2 start
-service mysql start
-svnserve -d -r /var/svn
+if ! service ntp start; then
+    echo -e "\033[1;91m"
+	echo "UOJ ERROR: ntp did not start successfully!"
+    echo -e "\033[0m"
+fi
 
-su local_main_judger -c '~/judge_client/judge_client start'
+if ! service mysql start; then
+    echo -e "\033[1;91m"
+	echo "UOJ ERROR: mysql did not start successfully!"
+    echo -e "\033[0m"
+fi
+
+if ! service apache2 start; then
+    echo -e "\033[1;91m"
+	echo "UOJ ERROR: apache2 did not start successfully!"
+    echo -e "\033[0m"
+fi
+
+if ! svnserve -d -r /var/svn; then
+    echo -e "\033[1;91m"
+	echo "UOJ ERROR: svn did not start successfully!"
+    echo -e "\033[0m"
+fi
+
+if ! su local_main_judger -c '~/judge_client/judge_client start'; then
+    echo -e "\033[1;91m"
+	echo "UOJ ERROR: judger did not start successfully!"
+    echo -e "\033[0m"
+fi
+
+echo "UOJ starts successfully!"
 
 exec bash
